### ISSUE TITLE
Realtime directional light shadow cascades disappear after baking the lighting in scene

### ISSUE THREAD

**Issue by KarlKroenenFFCR** [z3y/shaders#21]
after baking the lighting with either unity or bakery, the fading effect of the Realtime directional shadow cascades disappears, the issue is the same in all lighting modes (full lighting, indirect, subtractive).
this leads to a very sharp and sudden end to shadows after 135 meters (150 meters with cascade fading), shadows of objects at the edge of the line also pop in and out when they hit the max shadow caster distance at 150 meters.

Issue : 
![Screenshot_256](https://user-images.githubusercontent.com/62594188/213885116-5775a601-79c0-4d54-8398-10b377883b9c.png)

Expected Behavior :
![Screenshot_257](https://user-images.githubusercontent.com/62594188/213885139-b3be5244-b0e7-49da-82ef-70db278db8da.png)

**Comment by z3y** [comment]
This was probably fixed a while ago in the new version, but ill close it when i can confirm

**Comment by z3y** [comment]
Fixed on the dev branch
