### ISSUE TITLE
Question: Support for deferred rendering? 

### ISSUE THREAD

**Issue by Nolram12345** [z3y/shaders#28]
Hi there! 
Quick question - do these shaders support deferred rendering, or only forward?
Filament is a forward (clustered) renderer, so I was curious whether support for deferred rendering is provided.
Thanks !

**Comment by z3y** [comment]
This was targeted for VRChat, so forward rendering and  Built-In pipeline only. I really dont know anything about deferred to implement it

**Comment by Nolram12345** [comment]
Ah, that's what I feared. Quite unfortunate, but thanks for the answer regardless :)
Forward in Unity is more or less unused outside of VR and Mobile games, hence why it is unfortunate that this shader only supports forward.
